---
version: '3'
services:
  rainforest:
    build: .
  test:
    build:
      context: ./test
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: rspec test/spec.rb